#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Jul 01, 2016 12:45:51 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 480x211+446+152
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 994
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "AD Password"
    vTcl:DefineAlias "$top" "win01" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TLabel -background #d9d9d9
    ttk::style configure TLabel -foreground #000000
    ttk::style configure TLabel -font TkDefaultFont
    ttk::label $top.tLa40 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -justify center -textvariable lbl_pwd_expiration 
    vTcl:DefineAlias "$top.tLa40" "lbl_pwd_expires" vTcl:WidgetProc "win01" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu41 \
        -command bt_chg_pwd_clicked -takefocus {} -text {Change Password} 
    vTcl:DefineAlias "$top.tBu41" "bt_chg_pwd" vTcl:WidgetProc "win01" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu42 \
        -command bt_cancel_clicked -takefocus {} -text Cancel 
    vTcl:DefineAlias "$top.tBu42" "bt_cancel" vTcl:WidgetProc "win01" 1
    menu $top.m45 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa40 \
        -in $top -x 120 -y 40 -width 227 -height 17 -anchor nw \
        -bordermode ignore 
    place $top.tBu41 \
        -in $top -x 120 -y 160 -anchor nw -bordermode ignore 
    place $top.tBu42 \
        -in $top -x 260 -y 160 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

