#! /usr/bin/env python
#
# Support module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Jun 22, 2016 02:33:35 PM

import pexpect
import sys


def change_password(current_pwd,new_pwd1,new_pwd2):

    if (new_pwd1 != new_pwd2):
        return "Error: passwords do not match"

    child = pexpect.spawn('/usr/bin/kpasswd')
#    child.logfile = sys.stdout
    
    i=child.expect(["[Pp]assword for",pexpect.EOF])
    if i > 0:
        return "Error"
    child.sendline(current_pwd)

    i=child.expect(["Enter new password:", pexpect.EOF])
    print i
    if i > 0:
        return "Error: wrong old password"
    child.sendline(new_pwd1)
    
    i=child.expect(["Enter it again:",  pexpect.EOF])
    if i > 0:
        return "Error: wrong new password"
    child.sendline(new_pwd2)

    i=child.expect(["Password changed.", "Password change rejected:",  pexpect.EOF])
    if i > 0:
        return "Error: password rejected"

    return "OK"


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global old_pwd
    old_pwd = StringVar()

    global new_pwd1
    new_pwd1 = StringVar()

    global new_pwd2
    new_pwd2 = StringVar()

    global message
    message = StringVar()


def bt_cancel_clicked():
    sys.exit()

def bt_ok_clicked():
    m=change_password(old_pwd.get(), new_pwd1.get(), new_pwd2.get())
    print m
    message.set(m)
    if m == "OK":
        sys.exit()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import adpassword_change
    adpassword_change.vp_start_gui()


