#! /usr/bin/env python
#
# Support module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Jun 22, 2016 02:33:35 PM

import pexpect
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def change_password(current_pwd,new_pwd1,new_pwd2):
    if (new_pwd1 != new_pwd2):
        return "Error: passwords do not match"

    child = pexpect.spawn('/usr/bin/kpasswd')
    child.logfile = sys.stdout
    
    i=child.expect(["[Pp]assword for",pexpect.EOF])
    if i > 0:
        return "Error"
    child.sendline(current_pwd)

    i=child.expect(["Enter new password:", pexpect.EOF])
    print i
    if i > 0:
        return "Error: wrong old password"
    child.sendline(new_pwd1)
    
    i=child.expect(["Enter it again:",  pexpect.EOF])
    if i > 0:
        return "Error: wrong new password"
    child.sendline(new_pwd2)

    i=child.expect(["Password changed.", "Password change rejected:",  pexpect.EOF])
    if i > 0:
        return "Error: password rejected"

    return "OK"


def bt_cancel_clicked():
    print('adpassword_change_support.bt_cancel_clicked')
    print change_password(old_password, new_password1, new_password2)
    sys.exit()

def bt_ok_clicked():
    print('adpassword_change_support.bt_ok_clicked')
    
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import adpassword_change
    adpassword_change.vp_start_gui()


