#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Jun 22, 2016 02:33:21 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top46
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top46 {base} {
    if {$base == ""} {
        set base .top46
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 480x240+321+143
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 994
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "AD Password"
    vTcl:DefineAlias "$top" "win_chg_pwd" vTcl:Toplevel:WidgetProc "" 1
    ttk::label $top.tLa47 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Old Password} 
    vTcl:DefineAlias "$top.tLa47" "lbl_old_pwd" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::label $top.tLa48 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {New Password} 
    vTcl:DefineAlias "$top.tLa48" "lbl_new_pwd" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::entry $top.tEn49 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$top.tEn49" "TEntry1" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::label $top.tLa50 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Repeat New Password} 
    vTcl:DefineAlias "$top.tLa50" "lbl_rep_new_pwd" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::entry $top.tEn51 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$top.tEn51" "TEntry2" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::entry $top.tEn52 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$top.tEn52" "TEntry3" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu53 \
        -command bt_ok_clicked -takefocus {} -text Ok 
    vTcl:DefineAlias "$top.tBu53" "bt_ok" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu54 \
        -command bt_cancel_clicked -takefocus {} -text Cancel 
    vTcl:DefineAlias "$top.tBu54" "TButton2" vTcl:WidgetProc "win_chg_pwd" 1
    ttk::label $top.tLa57 \
        -background {#d9d9d9} -foreground {#f80000} -relief flat -text Tlabel 
    vTcl:DefineAlias "$top.tLa57" "TLabel4" vTcl:WidgetProc "win_chg_pwd" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa47 \
        -in $top -x 20 -y 20 -anchor nw -bordermode ignore 
    place $top.tLa48 \
        -in $top -x 20 -y 50 -anchor nw -bordermode ignore 
    place $top.tEn49 \
        -in $top -x 170 -y 20 -anchor nw -bordermode ignore 
    place $top.tLa50 \
        -in $top -x 20 -y 80 -anchor nw -bordermode ignore 
    place $top.tEn51 \
        -in $top -x 170 -y 50 -anchor nw -bordermode ignore 
    place $top.tEn52 \
        -in $top -x 170 -y 80 -anchor nw -bordermode ignore 
    place $top.tBu53 \
        -in $top -x 140 -y 190 -anchor nw -bordermode ignore 
    place $top.tBu54 \
        -in $top -x 250 -y 190 -anchor nw -bordermode ignore 
    place $top.tLa57 \
        -in $top -x 220 -y 130 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top46

